"""Generates addon/shadow_page.conf: the Euclidier shadow-mode GUI for force-shadow.

Style td3 (Acid's design language) recoloured: pastel lime chassis, charcoal boxes,
off-white buttons. Three tabs (hybrid layout, see DESIGN.md): LANES (8 strips),
DETAIL (ring + parameter knobs for the selected lane), PRESETS (+ randomizer).
Keys mirror the engine's control socket (euclidier.cpp "Control socket").

  python3 scripts/gen_shadow_page.py     # rewrites addon/shadow_page.conf
"""
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "addon" / "shadow_page.conf"

HEADER = '''# euclidier shadow-mode page -- GENERATED by scripts/gen_shadow_page.py, edit that instead.
#
# Tabs: LANES, DETAIL, PRESETS. Style td3, pastel lime chassis / off-white buttons.
# int_values=1: the engine's ctrl socket takes integers (enums by option index).
page=6
ctrl_sock=/tmp/euclidier_ctrl.sock
display_name="EUCLIDIER"
style=td3
theme_bg=c6e89a
theme_panel=c6e89a
theme_line=0e110e
theme_ink=f3f0e6
theme_ink_dim=9a9d92
theme_ink_faint=5f635a
theme_accent=c6e89a
theme_accent_hi=e4f7c4
theme_knob_face=2c312c
theme_knob_ring=050505
theme_bar=a9cc7a
theme_seg_active=c6e89a
theme_seg_inactive=2c312c
theme_seg_active_tx=1f2320
theme_btn_text=1f2320
theme_well=0e110e
theme_knob_off=4a4f48
theme_tab_on=1f2320
theme_lcd=0e110e
theme_box=1f2320
theme_btn_bg=f3f0e6
theme_chrome_ink=1f2320
theme_go_on=7ad34d
theme_go_off=ff6b4a
theme_tabs=a9cc7a
int_values=1
engine_process_name=euclidier
engine_nsmodule_path=/media/662522/AddOns/Euclidier/NSMODULE.json
engine_dirname=Euclidier
engine_arguments_json=[{"NAME":"use -v to hide output","VALUE":"-v"},{"NAME":"ctrl-sock flag","VALUE":"--ctrl-sock"},{"NAME":"control socket path","VALUE":"/tmp/euclidier_ctrl.sock"}]
'''

Y, H = 88, 624
L = []
def add(s): L.append(s)
def topbar():
    add('readout cx=690 cy=36 w=200 h=48 label="" get=transport')

# ---- LANES ----
add('[tab LANES]')
topbar()
add(f'frame x=36 y={Y} w=1208 h={H} title="LANES  (tap a row to select it for DETAIL)"')
top, pitch = 138, 71
for i in range(8):
    n = i + 1
    cy = top + i * pitch + 30
    add(f'toggle cx=112 cy={cy} label="{n}" key=l{n}_enable on=1')
    add(f'euclid cx=560 cy={cy} w=720 h=46 mode=strip key=sel val={i} get=l{n}_pattern')
    add(f'readout cx=1108 cy={cy} w=224 h=40 label="" get=l{n}_info')

# ---- DETAIL ----
add('[tab DETAIL]')
topbar()
add(f'frame x=36 y={Y} w=560 h={H} title="PATTERN"')
add('stepper cx=316 cy=172 w=340 h=48 label="" key=sel get=sel_name idx=sel min=0 max=7 numbered=0')
add('euclid cx=316 cy=446 w=460 h=460 mode=ring key="" val="" get=sel_pattern')
add(f'frame x=616 y={Y} w=628 h={H} title="LANE PARAMETERS"')
knobs = [("STEPS","steps",2,64),("FILL","fill",1,64),("SHIFT","shift",0,64),
         ("LOOP","loop",0,64),("NOTE","note",0,127),("GATE","gate",10,95),
         ("VELOCITY","vel",0,127),("HUMANIZE","velh",0,50),("CHANNEL","ch",1,15)]
for k, (lab, key, lo, hi) in enumerate(knobs):
    cx = 740 + (k % 3) * 190
    cy = 205 + (k // 3) * 150
    add(f'knob cx={cx} cy={cy} r=38 label="{lab}" key=sel_{key} min={lo} max={hi} pct=0')
add('stepper cx=760 cy=650 w=240 h=48 label="DIV" key=sel_div get=sel_div_txt idx=sel_div min=1 max=10 numbered=0')
add('enum_h cx=1015 cy=650 label="MODE" key=sel_mode options="NOTE,DRUM" active=0 sw=80')
add('toggle cx=1170 cy=650 label="ON" key=sel_enable on=1')

# ---- PRESETS ----
add('[tab PRESETS]')
topbar()
add(f'frame x=36 y={Y} w=800 h={H} title="PRESET SLOTS"')
add('list x=56 y=140 w=760 h=556 key=preset items=preset_list sel=preset cols=8 rows=7 th=56 gap=6 jump=0 colmajor=0 numbered=0 scale=1.5')
add(f'frame x=856 y={Y} w=388 h=200 title="PRESET"')
add('button cx=950 cy=200 label="LOAD" key=preset_load')
add('button cx=1150 cy=200 label="SAVE" key=preset_save')
add(f'frame x=856 y=300 w=388 h=412 title="RANDOMIZE"')
add('stepper cx=1050 cy=420 w=320 h=48 label="LANES" key=rand_lane get=rand_lane_txt idx=rand_lane min=0 max=10 numbered=0')
add('button cx=1050 cy=560 label="RANDOMIZE" key=rand_go')

OUT.parent.mkdir(exist_ok=True)
OUT.write_text(HEADER + "\n" + "\n".join(L) + "\n")
print("wrote", OUT, len(L), "lines")
